version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redisdata:/data

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - postgresdata:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - pgadmindata:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  redisdata:
    driver: local
  postgresdata:
    driver: local
  pgadmindata:
    driver: local

networks:
  postgres:
    driver: bridge
  esnet:
